### ISSUE TITLE
Doesn't work BUT ...

### ISSUE THREAD

**Issue by lippih** [kamranayub/picam-viewer#1]
... I think it's a problem from picam! The player doesn't play the HLS Stream from picam, but it plays other streams from the net. I tried also VLC, to see if I have some errors with my server;  VLC has no problems to play the HLS Stream from picam. So the combination videojs-contrib-hls and picam doesn't work, perhaps someone can tell me why? Perhaps its a problem with the index.m3u8 generated from picam?

**Comment by kamranayub** [comment]
What browser are you using to test? I use Chrome and haven't had issues
streaming Picam with the viewer. You can also open the developer tools in
Chrome and see if there are any errors. Maybe it's just a bad path.

**Comment by hazardary** [comment]
Hi,
I also have the same problem. I can view the stream correctly followed your post but the webpage doesn't working. I have tried chrome and edge and ie. Inspect the webpage, I found:

<video id="player_html5_api" preload="auto" class="vjs-tech" tabindex="-1" src="blob:http://192.168.1.159/36fb2a67-5dc2-4609-a728-becf89bd6d95"></video>

I know nothing about js and I don't know how to tell if it grab the right path. Also, how can you redirect the web address http://babypi.local/ to this address? I have to use http://babypi.local/picam-viewer/index.html to see the player.

**Comment by kamranayub** [comment]
Actually it sounds like you may not have configured nginx correctly, the root should be pointing to your picam-viewer path, so the URL should just be http://babypi.local not http://babypi.local/picam-viewer

I can double check the guide, it should be configuring it that way unless you missed a command or the guide missed something. But yeah that's my guess!

Also I noticed I can no longer use the shortcut DNS babypi.local, I have been using the IP address for the past year or two. I can add that note as well.

**Comment by hazardary** [comment]
Thanks a lot. I got it fixed. I changed
root /var/www/html
to
root /var/www/html/picam-viewer

in nginx default config. I think you didn't mention this in "Adding a web player" section. Great tutorial. Thanks again.

**Comment by kamranayub** [comment]
Perfect, I will add this to the guide! Appreciate it!
