### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by meatalhead** [kamranayub/picam-viewer#3]
I think I'm doing something obvious wrong, when I run: 
` sudo git clone https://github.com/kamranayub/picam-viewer.git .`

I get the following error:
`fatal: destination path '.' already exists and is not an empty directory.`

Any idea what I'm doing wrong?

**Comment by carlmcqueen** [comment]
Just delete the nginx index file and it will copy in fine.

**Comment by kamranayub** [comment]
Ah yeah, it needs to be an empty directory

**Comment by meatalhead** [comment]
Ok will do thanks, so next question, where's the index file? `/etc/nginx`?

**Comment by meatalhead** [comment]
Thanks
